### ISSUE TITLE
Neue suche 2018

### ISSUE THREAD

**Issue by tpmodding** [SciLor/mydealz-krokodeal-jagd-2016#1]
Gibt ne Jagd, wirst du es Updaten? :-)  und falls ja, wie funktioniert dein Skript :-P

**Comment by SciLor** [comment]
Mir fehlt leider die Zeit.
Eigentlich nur in die Javascript console kopieren.

**Comment by monoxacc** [comment]
You can try this it will be updated constantly:  https://github.com/monoxacc/krokodeal-2016
